---
title: "PP_for_DS"
author: "Andrii Zadaianchuk"
date: "December 16, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r code 1}
library(parallel)

jloop <- function(ichunk) {
   tot <- 0
   nr <- nrow(lnks)
   for (i in ichunk) {
      tmp <- lnks[(i+1):nr,] %*% lnks[i,]
      tot <- tot + sum(tmp)
   }
   tot
}

mutoutpar <- function(cls) {
   nr <- nrow(lnks)  # lnks global
   clusterExport(cls,"lnks")
   ichunks <- clusterSplit(cls,1:(nr-1))
   tots <- clusterApply(cls,ichunks,jloop)
   Reduce(sum,tots) / nr
}

# sim on matrix of size nr x nc, on cluster cls
sim <- function(nr,nc,cls) {
   lnks <<- matrix(sample(0:1,(nr*nc),replace=TRUE),nrow=nr)
   print(system.time(mutoutpar(cls)))
}

init <- function(nworkers) {
   makeCluster(nworkers) # return cluster object
}
```



```{r code 2}

mutoutser<- function(links) {
   nr <- nrow(links)
   nc <- ncol(links)
   tot = 0
   for (i in 1:(nr-1)) {
      for (j in (i+1):nr) {
         for (k in 1:nc) 
            tot <- tot + links[i,k] * links[j,k]
      }
   }
   tot / nr
}

mutoutser1<- function(links) {
   nr <- nrow(links)
   nc <- ncol(links)
   tot <- 0
   for (i in 1:(nr-1)) {
      tmp <- links[(i+1):nr,] %*% links[i,]
      tot <- tot + sum(tmp)
   }
   tot / nr
}

sim <- function(nr,nc) {
   lnk <- matrix(sample(0:1,(nr*nc),replace=TRUE),nrow=nr)
   print(system.time(mutoutser(lnk)))
   print(system.time(mutoutser1(lnk)))
}

```

